image: maven:3.9.5-eclipse-temurin-21

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/

stages:
  - build
  - test
  - package
  - deploy

default:
  tags:
    - hva

build:
  stage: build
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

test:
  stage: test
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
    when: always

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

deploy:dev:
  stage: deploy
  script:
    - echo "Deploying to DEV environment..."
    - echo "JAR file:" target/*.jar
    # Add your deployment commands here
    # Example: scp target/*.jar user@dev-server:/path/to/deploy/
    # Example: ssh user@dev-server "java -jar /path/to/deploy/webstore.jar"
  environment:
    name: development
    url: http://dev.yourapp.com
  only:
    - develop
    - dev

deploy:test:
  stage: deploy
  script:
    - echo "Deploying to TEST environment..."
    - echo "JAR file:" target/*.jar
    # Add your deployment commands here
    # Example: scp target/*.jar user@test-server:/path/to/deploy/
  environment:
    name: testing
    url: http://test.yourapp.com
  only:
    - test
  when: manual

deploy:prod:
  stage: deploy
  script:
    - echo "Deploying to PRODUCTION environment..."
    - echo "JAR file:" target/*.jar
    # Add your deployment commands here
    # Example: scp target/*.jar user@prod-server:/path/to/deploy/
  environment:
    name: production
    url: http://yourapp.com
  only:
    - main
    - master
  when: manual