version: '3.8'

services:
  webstore:
    build: .
    container_name: webstore-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: unless-stopped