services:
  bookstore-api:
    build: 
      context: ./backend
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Development}
    ports:
      - "${API_PORT:-5236}:80"

  bookstore-frontend:
    build: 
      context: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost:${API_PORT:-5236}
      - REACT_APP_ENVIRONMENT=${ENVIRONMENT:-development}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - bookstore-api


# Optional: SonarQube for when you need code analysis
# Uncomment when you want to run code quality checks
# 
# To enable SonarQube, uncomment below and run:
# docker-compose up -d sonarqube
# Then access it at http://localhost:9000 (admin/admin)
#
# services:
#   sonarqube:
#     image: sonarqube:community
#     environment:
#       - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
#       - SONAR_JDBC_URL=jdbc:h2:mem:sonar
#     ports:
#       - "9000:9000"
#     networks:
#       - bookstore-network
#     volumes:
#       - sonarqube_data:/opt/sonarqube/data
#       - sonarqube_logs:/opt/sonarqube/logs
#       - sonarqube_extensions:/opt/sonarqube/extensions
#
# volumes:
#   sonarqube_data:
#   sonarqube_logs:
#   sonarqube_extensions: