version: '3.8'

services:
  # Backend API
  bookstore-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT:-Development}
    ports:
      - "${API_PORT:-5000}:80"
    networks:
      - bookstore-network
    volumes:
      - ./backend:/app/source

  # Frontend
  bookstore-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:${API_PORT:-5000}
        - REACT_APP_ENVIRONMENT=${ENVIRONMENT:-development}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - bookstore-api
    networks:
      - bookstore-network

  # SonarQube for static code analysis
  sonarqube:
    image: sonarqube:community
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    networks:
      - bookstore-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  bookstore-network:
    driver: bridge
